// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simpledb.proto

package simpledb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_748391160b9263c4, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type HostStatsReplyMsg struct {
	TotalMemory          string   `protobuf:"bytes,1,opt,name=totalMemory,proto3" json:"totalMemory,omitempty"`
	UsedMemory           string   `protobuf:"bytes,2,opt,name=usedMemory,proto3" json:"usedMemory,omitempty"`
	TotalSpace           string   `protobuf:"bytes,3,opt,name=totalSpace,proto3" json:"totalSpace,omitempty"`
	UsedSpace            string   `protobuf:"bytes,4,opt,name=usedSpace,proto3" json:"usedSpace,omitempty"`
	NumCores             string   `protobuf:"bytes,5,opt,name=numCores,proto3" json:"numCores,omitempty"`
	CpuPercent           string   `protobuf:"bytes,6,opt,name=cpuPercent,proto3" json:"cpuPercent,omitempty"`
	Os                   string   `protobuf:"bytes,7,opt,name=os,proto3" json:"os,omitempty"`
	Hostname             string   `protobuf:"bytes,8,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Uptime               string   `protobuf:"bytes,9,opt,name=uptime,proto3" json:"uptime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostStatsReplyMsg) Reset()         { *m = HostStatsReplyMsg{} }
func (m *HostStatsReplyMsg) String() string { return proto.CompactTextString(m) }
func (*HostStatsReplyMsg) ProtoMessage()    {}
func (*HostStatsReplyMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_748391160b9263c4, []int{1}
}

func (m *HostStatsReplyMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostStatsReplyMsg.Unmarshal(m, b)
}
func (m *HostStatsReplyMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostStatsReplyMsg.Marshal(b, m, deterministic)
}
func (m *HostStatsReplyMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostStatsReplyMsg.Merge(m, src)
}
func (m *HostStatsReplyMsg) XXX_Size() int {
	return xxx_messageInfo_HostStatsReplyMsg.Size(m)
}
func (m *HostStatsReplyMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_HostStatsReplyMsg.DiscardUnknown(m)
}

var xxx_messageInfo_HostStatsReplyMsg proto.InternalMessageInfo

func (m *HostStatsReplyMsg) GetTotalMemory() string {
	if m != nil {
		return m.TotalMemory
	}
	return ""
}

func (m *HostStatsReplyMsg) GetUsedMemory() string {
	if m != nil {
		return m.UsedMemory
	}
	return ""
}

func (m *HostStatsReplyMsg) GetTotalSpace() string {
	if m != nil {
		return m.TotalSpace
	}
	return ""
}

func (m *HostStatsReplyMsg) GetUsedSpace() string {
	if m != nil {
		return m.UsedSpace
	}
	return ""
}

func (m *HostStatsReplyMsg) GetNumCores() string {
	if m != nil {
		return m.NumCores
	}
	return ""
}

func (m *HostStatsReplyMsg) GetCpuPercent() string {
	if m != nil {
		return m.CpuPercent
	}
	return ""
}

func (m *HostStatsReplyMsg) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *HostStatsReplyMsg) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *HostStatsReplyMsg) GetUptime() string {
	if m != nil {
		return m.Uptime
	}
	return ""
}

type KeyMsg struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyMsg) Reset()         { *m = KeyMsg{} }
func (m *KeyMsg) String() string { return proto.CompactTextString(m) }
func (*KeyMsg) ProtoMessage()    {}
func (*KeyMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_748391160b9263c4, []int{2}
}

func (m *KeyMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyMsg.Unmarshal(m, b)
}
func (m *KeyMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyMsg.Marshal(b, m, deterministic)
}
func (m *KeyMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyMsg.Merge(m, src)
}
func (m *KeyMsg) XXX_Size() int {
	return xxx_messageInfo_KeyMsg.Size(m)
}
func (m *KeyMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyMsg.DiscardUnknown(m)
}

var xxx_messageInfo_KeyMsg proto.InternalMessageInfo

func (m *KeyMsg) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type KeyValueMsg struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValueMsg) Reset()         { *m = KeyValueMsg{} }
func (m *KeyValueMsg) String() string { return proto.CompactTextString(m) }
func (*KeyValueMsg) ProtoMessage()    {}
func (*KeyValueMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_748391160b9263c4, []int{3}
}

func (m *KeyValueMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValueMsg.Unmarshal(m, b)
}
func (m *KeyValueMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValueMsg.Marshal(b, m, deterministic)
}
func (m *KeyValueMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValueMsg.Merge(m, src)
}
func (m *KeyValueMsg) XXX_Size() int {
	return xxx_messageInfo_KeyValueMsg.Size(m)
}
func (m *KeyValueMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValueMsg.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValueMsg proto.InternalMessageInfo

func (m *KeyValueMsg) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValueMsg) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type KeyValuesMsg struct {
	Pairs                []*KeyValueMsg `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *KeyValuesMsg) Reset()         { *m = KeyValuesMsg{} }
func (m *KeyValuesMsg) String() string { return proto.CompactTextString(m) }
func (*KeyValuesMsg) ProtoMessage()    {}
func (*KeyValuesMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_748391160b9263c4, []int{4}
}

func (m *KeyValuesMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValuesMsg.Unmarshal(m, b)
}
func (m *KeyValuesMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValuesMsg.Marshal(b, m, deterministic)
}
func (m *KeyValuesMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValuesMsg.Merge(m, src)
}
func (m *KeyValuesMsg) XXX_Size() int {
	return xxx_messageInfo_KeyValuesMsg.Size(m)
}
func (m *KeyValuesMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValuesMsg.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValuesMsg proto.InternalMessageInfo

func (m *KeyValuesMsg) GetPairs() []*KeyValueMsg {
	if m != nil {
		return m.Pairs
	}
	return nil
}

type OkMsg struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OkMsg) Reset()         { *m = OkMsg{} }
func (m *OkMsg) String() string { return proto.CompactTextString(m) }
func (*OkMsg) ProtoMessage()    {}
func (*OkMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_748391160b9263c4, []int{5}
}

func (m *OkMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OkMsg.Unmarshal(m, b)
}
func (m *OkMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OkMsg.Marshal(b, m, deterministic)
}
func (m *OkMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OkMsg.Merge(m, src)
}
func (m *OkMsg) XXX_Size() int {
	return xxx_messageInfo_OkMsg.Size(m)
}
func (m *OkMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_OkMsg.DiscardUnknown(m)
}

var xxx_messageInfo_OkMsg proto.InternalMessageInfo

func (m *OkMsg) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type RemoteNodeMsg struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Id                   []byte   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	IsLeader             bool     `protobuf:"varint,3,opt,name=isLeader,proto3" json:"isLeader,omitempty"`
	IsElection           bool     `protobuf:"varint,4,opt,name=isElection,proto3" json:"isElection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteNodeMsg) Reset()         { *m = RemoteNodeMsg{} }
func (m *RemoteNodeMsg) String() string { return proto.CompactTextString(m) }
func (*RemoteNodeMsg) ProtoMessage()    {}
func (*RemoteNodeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_748391160b9263c4, []int{6}
}

func (m *RemoteNodeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteNodeMsg.Unmarshal(m, b)
}
func (m *RemoteNodeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteNodeMsg.Marshal(b, m, deterministic)
}
func (m *RemoteNodeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteNodeMsg.Merge(m, src)
}
func (m *RemoteNodeMsg) XXX_Size() int {
	return xxx_messageInfo_RemoteNodeMsg.Size(m)
}
func (m *RemoteNodeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteNodeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteNodeMsg proto.InternalMessageInfo

func (m *RemoteNodeMsg) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *RemoteNodeMsg) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *RemoteNodeMsg) GetIsLeader() bool {
	if m != nil {
		return m.IsLeader
	}
	return false
}

func (m *RemoteNodeMsg) GetIsElection() bool {
	if m != nil {
		return m.IsElection
	}
	return false
}

type RemoteNodesMsg struct {
	RemoteNodes          []*RemoteNodeMsg `protobuf:"bytes,1,rep,name=remoteNodes,proto3" json:"remoteNodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RemoteNodesMsg) Reset()         { *m = RemoteNodesMsg{} }
func (m *RemoteNodesMsg) String() string { return proto.CompactTextString(m) }
func (*RemoteNodesMsg) ProtoMessage()    {}
func (*RemoteNodesMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_748391160b9263c4, []int{7}
}

func (m *RemoteNodesMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteNodesMsg.Unmarshal(m, b)
}
func (m *RemoteNodesMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteNodesMsg.Marshal(b, m, deterministic)
}
func (m *RemoteNodesMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteNodesMsg.Merge(m, src)
}
func (m *RemoteNodesMsg) XXX_Size() int {
	return xxx_messageInfo_RemoteNodesMsg.Size(m)
}
func (m *RemoteNodesMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteNodesMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteNodesMsg proto.InternalMessageInfo

func (m *RemoteNodesMsg) GetRemoteNodes() []*RemoteNodeMsg {
	if m != nil {
		return m.RemoteNodes
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "simpledb.Empty")
	proto.RegisterType((*HostStatsReplyMsg)(nil), "simpledb.HostStatsReplyMsg")
	proto.RegisterType((*KeyMsg)(nil), "simpledb.KeyMsg")
	proto.RegisterType((*KeyValueMsg)(nil), "simpledb.KeyValueMsg")
	proto.RegisterType((*KeyValuesMsg)(nil), "simpledb.KeyValuesMsg")
	proto.RegisterType((*OkMsg)(nil), "simpledb.OkMsg")
	proto.RegisterType((*RemoteNodeMsg)(nil), "simpledb.RemoteNodeMsg")
	proto.RegisterType((*RemoteNodesMsg)(nil), "simpledb.RemoteNodesMsg")
}

func init() { proto.RegisterFile("simpledb.proto", fileDescriptor_748391160b9263c4) }

var fileDescriptor_748391160b9263c4 = []byte{
	// 523 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0xc5, 0x72, 0xec, 0xc8, 0xa3, 0xd4, 0x76, 0x96, 0x36, 0x11, 0x6e, 0x29, 0x46, 0xa7, 0x40,
	0x21, 0x94, 0x94, 0x14, 0x8a, 0x7b, 0x29, 0x71, 0x70, 0x5a, 0xd7, 0x75, 0x91, 0x4b, 0xee, 0x6b,
	0x6b, 0x92, 0x0a, 0x4b, 0x5a, 0xb1, 0xbb, 0x2a, 0xf8, 0x77, 0xf4, 0x6f, 0xf6, 0x47, 0x94, 0x1d,
	0xc9, 0x96, 0x82, 0xe5, 0xdc, 0x34, 0x6f, 0xde, 0x9b, 0x8f, 0x37, 0x8b, 0xa0, 0xab, 0xc2, 0x38,
	0x8d, 0x30, 0x58, 0x5e, 0xa6, 0x52, 0x68, 0xc1, 0xec, 0x6d, 0xec, 0x1d, 0x43, 0xeb, 0x36, 0x4e,
	0xf5, 0xc6, 0xfb, 0x6b, 0xc1, 0xe9, 0x9d, 0x50, 0x7a, 0xa1, 0xb9, 0x56, 0x3e, 0xa6, 0xd1, 0x66,
	0xa6, 0x1e, 0xd9, 0x10, 0x1c, 0x2d, 0x34, 0x8f, 0x66, 0x18, 0x0b, 0xb9, 0x71, 0x1b, 0xc3, 0xc6,
	0x45, 0xc7, 0xaf, 0x42, 0xec, 0x2d, 0x40, 0xa6, 0x30, 0x28, 0x08, 0x16, 0x11, 0x2a, 0x88, 0xc9,
	0x13, 0x7d, 0x91, 0xf2, 0x15, 0xba, 0xcd, 0x3c, 0x5f, 0x22, 0xec, 0x0d, 0x74, 0x0c, 0x3b, 0x4f,
	0x1f, 0x51, 0xba, 0x04, 0xd8, 0x00, 0xec, 0x24, 0x8b, 0x6f, 0x84, 0x44, 0xe5, 0xb6, 0x28, 0xb9,
	0x8b, 0x4d, 0xe5, 0x55, 0x9a, 0xfd, 0x44, 0xb9, 0xc2, 0x44, 0xbb, 0xed, 0xbc, 0x72, 0x89, 0xb0,
	0x2e, 0x58, 0x42, 0xb9, 0xc7, 0x84, 0x5b, 0x42, 0x99, 0x5a, 0xbf, 0x85, 0xd2, 0x09, 0x8f, 0xd1,
	0xb5, 0xf3, 0x5a, 0xdb, 0x98, 0x9d, 0x41, 0x3b, 0x4b, 0x75, 0x18, 0xa3, 0xdb, 0xa1, 0x4c, 0x11,
	0x79, 0x03, 0x68, 0x4f, 0x91, 0x9c, 0xe8, 0x43, 0x73, 0x8d, 0x5b, 0x07, 0xcc, 0xa7, 0x77, 0x0d,
	0xce, 0x14, 0x37, 0xf7, 0x3c, 0xca, 0xb0, 0x96, 0xc0, 0x5e, 0x42, 0xeb, 0x8f, 0xc9, 0x16, 0xae,
	0xe4, 0x81, 0x37, 0x82, 0x93, 0xad, 0x4c, 0x19, 0xdd, 0x3b, 0x68, 0xa5, 0x3c, 0x94, 0xca, 0x6d,
	0x0c, 0x9b, 0x17, 0xce, 0xd5, 0xab, 0xcb, 0xdd, 0xad, 0x2a, 0xd5, 0xfd, 0x9c, 0xe3, 0x9d, 0x43,
	0x6b, 0xbe, 0x36, 0xaa, 0x2e, 0x58, 0xf3, 0x35, 0x35, 0xb3, 0x7d, 0x6b, 0xbe, 0xf6, 0x04, 0xbc,
	0xf0, 0x31, 0x16, 0x1a, 0x7f, 0x88, 0x80, 0xc6, 0x61, 0x70, 0xc4, 0x83, 0x40, 0x16, 0xf3, 0xd0,
	0xb7, 0x11, 0x85, 0x01, 0x4d, 0x73, 0xe2, 0x5b, 0x61, 0x60, 0x1c, 0x09, 0xd5, 0x77, 0xe4, 0x01,
	0x4a, 0xba, 0x8c, 0xed, 0xef, 0x62, 0xe3, 0x6e, 0xa8, 0x6e, 0x23, 0x5c, 0xe9, 0x50, 0x24, 0x74,
	0x18, 0xdb, 0xaf, 0x20, 0xde, 0x14, 0xba, 0x65, 0x43, 0x5a, 0xe4, 0x13, 0x38, 0xb2, 0x44, 0x8a,
	0x75, 0xce, 0xcb, 0x75, 0x9e, 0xcc, 0xe7, 0x57, 0xb9, 0x57, 0xff, 0x9a, 0x60, 0x2f, 0x88, 0x37,
	0x5e, 0xb2, 0xf7, 0xe0, 0x8c, 0x31, 0x9a, 0xde, 0xdf, 0xf0, 0x28, 0x42, 0xc9, 0xfa, 0x4f, 0x0c,
	0x99, 0xa9, 0xc7, 0x41, 0xaf, 0x44, 0x72, 0x33, 0xbe, 0xc0, 0xe9, 0x04, 0xb5, 0x79, 0xbd, 0x5f,
	0x93, 0x07, 0x51, 0xe8, 0x2a, 0x2c, 0x7a, 0xe1, 0x83, 0xd7, 0x25, 0xb0, 0xff, 0xd0, 0x3f, 0x82,
	0x33, 0x41, 0xfd, 0x4c, 0xd3, 0xfa, 0xbb, 0xb0, 0x11, 0x74, 0x27, 0xa8, 0x69, 0x8b, 0x43, 0x7d,
	0xdd, 0x3a, 0x0b, 0xc8, 0xb1, 0xcf, 0xd0, 0xbb, 0x43, 0x2e, 0xf5, 0x12, 0xb9, 0x2e, 0xd4, 0x07,
	0xc9, 0xfb, 0x5b, 0x8f, 0xa1, 0xf7, 0x4d, 0x84, 0x49, 0xb5, 0xf7, 0x21, 0xb7, 0x9f, 0x99, 0xe1,
	0x1a, 0x9c, 0x45, 0x65, 0xf1, 0xfa, 0x35, 0xf7, 0x9b, 0x8f, 0xa0, 0xff, 0x4b, 0xf2, 0x44, 0x3d,
	0xa0, 0xdc, 0x69, 0xcf, 0xf6, 0xb5, 0xb5, 0x93, 0x2f, 0xdb, 0xf4, 0x17, 0xfa, 0xf0, 0x3f, 0x00,
	0x00, 0xff, 0xff, 0x53, 0x2c, 0x09, 0xbb, 0x97, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SimpleDbClient is the client API for SimpleDb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SimpleDbClient interface {
	DelKVCaller(ctx context.Context, in *KeyMsg, opts ...grpc.CallOption) (*OkMsg, error)
	GetHostInfoCaller(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HostStatsReplyMsg, error)
	GetKVCaller(ctx context.Context, in *KeyMsg, opts ...grpc.CallOption) (*KeyValueMsg, error)
	GetNodesCaller(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RemoteNodesMsg, error)
	HeartbeatCaller(ctx context.Context, in *RemoteNodesMsg, opts ...grpc.CallOption) (*OkMsg, error)
	JoinNodesCaller(ctx context.Context, in *RemoteNodeMsg, opts ...grpc.CallOption) (*RemoteNodesMsg, error)
	SetKVCaller(ctx context.Context, in *KeyValueMsg, opts ...grpc.CallOption) (*OkMsg, error)
	TransferKVCaller(ctx context.Context, in *KeyValuesMsg, opts ...grpc.CallOption) (*OkMsg, error)
}

type simpleDbClient struct {
	cc *grpc.ClientConn
}

func NewSimpleDbClient(cc *grpc.ClientConn) SimpleDbClient {
	return &simpleDbClient{cc}
}

func (c *simpleDbClient) DelKVCaller(ctx context.Context, in *KeyMsg, opts ...grpc.CallOption) (*OkMsg, error) {
	out := new(OkMsg)
	err := c.cc.Invoke(ctx, "/simpledb.SimpleDb/DelKVCaller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simpleDbClient) GetHostInfoCaller(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HostStatsReplyMsg, error) {
	out := new(HostStatsReplyMsg)
	err := c.cc.Invoke(ctx, "/simpledb.SimpleDb/GetHostInfoCaller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simpleDbClient) GetKVCaller(ctx context.Context, in *KeyMsg, opts ...grpc.CallOption) (*KeyValueMsg, error) {
	out := new(KeyValueMsg)
	err := c.cc.Invoke(ctx, "/simpledb.SimpleDb/GetKVCaller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simpleDbClient) GetNodesCaller(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RemoteNodesMsg, error) {
	out := new(RemoteNodesMsg)
	err := c.cc.Invoke(ctx, "/simpledb.SimpleDb/GetNodesCaller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simpleDbClient) HeartbeatCaller(ctx context.Context, in *RemoteNodesMsg, opts ...grpc.CallOption) (*OkMsg, error) {
	out := new(OkMsg)
	err := c.cc.Invoke(ctx, "/simpledb.SimpleDb/HeartbeatCaller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simpleDbClient) JoinNodesCaller(ctx context.Context, in *RemoteNodeMsg, opts ...grpc.CallOption) (*RemoteNodesMsg, error) {
	out := new(RemoteNodesMsg)
	err := c.cc.Invoke(ctx, "/simpledb.SimpleDb/JoinNodesCaller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simpleDbClient) SetKVCaller(ctx context.Context, in *KeyValueMsg, opts ...grpc.CallOption) (*OkMsg, error) {
	out := new(OkMsg)
	err := c.cc.Invoke(ctx, "/simpledb.SimpleDb/SetKVCaller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simpleDbClient) TransferKVCaller(ctx context.Context, in *KeyValuesMsg, opts ...grpc.CallOption) (*OkMsg, error) {
	out := new(OkMsg)
	err := c.cc.Invoke(ctx, "/simpledb.SimpleDb/TransferKVCaller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimpleDbServer is the server API for SimpleDb service.
type SimpleDbServer interface {
	DelKVCaller(context.Context, *KeyMsg) (*OkMsg, error)
	GetHostInfoCaller(context.Context, *Empty) (*HostStatsReplyMsg, error)
	GetKVCaller(context.Context, *KeyMsg) (*KeyValueMsg, error)
	GetNodesCaller(context.Context, *Empty) (*RemoteNodesMsg, error)
	HeartbeatCaller(context.Context, *RemoteNodesMsg) (*OkMsg, error)
	JoinNodesCaller(context.Context, *RemoteNodeMsg) (*RemoteNodesMsg, error)
	SetKVCaller(context.Context, *KeyValueMsg) (*OkMsg, error)
	TransferKVCaller(context.Context, *KeyValuesMsg) (*OkMsg, error)
}

// UnimplementedSimpleDbServer can be embedded to have forward compatible implementations.
type UnimplementedSimpleDbServer struct {
}

func (*UnimplementedSimpleDbServer) DelKVCaller(ctx context.Context, req *KeyMsg) (*OkMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelKVCaller not implemented")
}
func (*UnimplementedSimpleDbServer) GetHostInfoCaller(ctx context.Context, req *Empty) (*HostStatsReplyMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostInfoCaller not implemented")
}
func (*UnimplementedSimpleDbServer) GetKVCaller(ctx context.Context, req *KeyMsg) (*KeyValueMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKVCaller not implemented")
}
func (*UnimplementedSimpleDbServer) GetNodesCaller(ctx context.Context, req *Empty) (*RemoteNodesMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodesCaller not implemented")
}
func (*UnimplementedSimpleDbServer) HeartbeatCaller(ctx context.Context, req *RemoteNodesMsg) (*OkMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartbeatCaller not implemented")
}
func (*UnimplementedSimpleDbServer) JoinNodesCaller(ctx context.Context, req *RemoteNodeMsg) (*RemoteNodesMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinNodesCaller not implemented")
}
func (*UnimplementedSimpleDbServer) SetKVCaller(ctx context.Context, req *KeyValueMsg) (*OkMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetKVCaller not implemented")
}
func (*UnimplementedSimpleDbServer) TransferKVCaller(ctx context.Context, req *KeyValuesMsg) (*OkMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferKVCaller not implemented")
}

func RegisterSimpleDbServer(s *grpc.Server, srv SimpleDbServer) {
	s.RegisterService(&_SimpleDb_serviceDesc, srv)
}

func _SimpleDb_DelKVCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleDbServer).DelKVCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simpledb.SimpleDb/DelKVCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleDbServer).DelKVCaller(ctx, req.(*KeyMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimpleDb_GetHostInfoCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleDbServer).GetHostInfoCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simpledb.SimpleDb/GetHostInfoCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleDbServer).GetHostInfoCaller(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimpleDb_GetKVCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleDbServer).GetKVCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simpledb.SimpleDb/GetKVCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleDbServer).GetKVCaller(ctx, req.(*KeyMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimpleDb_GetNodesCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleDbServer).GetNodesCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simpledb.SimpleDb/GetNodesCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleDbServer).GetNodesCaller(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimpleDb_HeartbeatCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoteNodesMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleDbServer).HeartbeatCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simpledb.SimpleDb/HeartbeatCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleDbServer).HeartbeatCaller(ctx, req.(*RemoteNodesMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimpleDb_JoinNodesCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoteNodeMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleDbServer).JoinNodesCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simpledb.SimpleDb/JoinNodesCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleDbServer).JoinNodesCaller(ctx, req.(*RemoteNodeMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimpleDb_SetKVCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValueMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleDbServer).SetKVCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simpledb.SimpleDb/SetKVCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleDbServer).SetKVCaller(ctx, req.(*KeyValueMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimpleDb_TransferKVCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValuesMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleDbServer).TransferKVCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simpledb.SimpleDb/TransferKVCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleDbServer).TransferKVCaller(ctx, req.(*KeyValuesMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _SimpleDb_serviceDesc = grpc.ServiceDesc{
	ServiceName: "simpledb.SimpleDb",
	HandlerType: (*SimpleDbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DelKVCaller",
			Handler:    _SimpleDb_DelKVCaller_Handler,
		},
		{
			MethodName: "GetHostInfoCaller",
			Handler:    _SimpleDb_GetHostInfoCaller_Handler,
		},
		{
			MethodName: "GetKVCaller",
			Handler:    _SimpleDb_GetKVCaller_Handler,
		},
		{
			MethodName: "GetNodesCaller",
			Handler:    _SimpleDb_GetNodesCaller_Handler,
		},
		{
			MethodName: "HeartbeatCaller",
			Handler:    _SimpleDb_HeartbeatCaller_Handler,
		},
		{
			MethodName: "JoinNodesCaller",
			Handler:    _SimpleDb_JoinNodesCaller_Handler,
		},
		{
			MethodName: "SetKVCaller",
			Handler:    _SimpleDb_SetKVCaller_Handler,
		},
		{
			MethodName: "TransferKVCaller",
			Handler:    _SimpleDb_TransferKVCaller_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "simpledb.proto",
}
